=== AlexanerP/Task2/src/main/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.by/goods"
        xmlns:tns="http://www.epam.by/goods">

    <element name="goods">
        <complexType>
            <sequence>
                <element name="items">
                    <complexType>
                        <sequence>
                            <choice minOccurs="0" maxOccurs="unbounded">
                                <element name="smoothing-iron" type="tns:smoothing-iron"/>
                                <element name="refrigerator" type="tns:refrigerator"/>
                            </choice>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="smoothing-iron">
        <sequence>
            <element name="type" type="string"/>
            <element name="id" type="long"/>
            <element name="company" type="string"/>
            <element name="name" type="string"/>
            <element name="price" type="double"/>
            <element name="count-mode" type="int"/>
            <element name="max-temperature" type="int"/>
        </sequence>
    </complexType>

    <complexType name="refrigerator">
        <sequence>
            <element name="type" type="string"/>
            <element name="id" type="long"/>
            <element name="company" type="string"/>
            <element name="name" type="string"/>
            <element name="price" type="double"/>
            <element name="volume-freezer" type="double"/>
            <element name="volume-not-freezer" type="double"/>
        </sequence>
    </complexType>
</schema>

=== AlexanerP/Task2/src/main/resources/Storage.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<n:goods xmlns:n="http://www.epam.by/goods" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.epam.by/goods schema.xsd">
        <items>
            <smoothing-iron>
                <type>Smoothing Iron</type>
                <id>1</id>
                <company>LG</company>
                <name>S153.I8</name>
                <price>19.9</price>
                <count-mode>5</count-mode>
                <max-temperature>570</max-temperature>
            </smoothing-iron>
            <refrigerator>
                <type>Refrigerator</type>
                <id>1</id>
                <company>Indesit</company>
                <name>MAF 3000</name>
                <price>1966.2</price>
                <volume-freezer>15</volume-freezer>
                <volume-not-freezer>5</volume-not-freezer>
            </refrigerator>
            <smoothing-iron>
                <type>Smoothing Iron</type>
                <id>3</id>
                <company>AlG</company>
                <name>S1INNS 53.I8</name>
                <price>30</price>
                <count-mode>2</count-mode>
                <max-temperature>170</max-temperature>
            </smoothing-iron>
            <refrigerator>
                <type>Refrigerator</type>
                <id>4</id>
                <company>Mi</company>
                <name>Son S55</name>
                <price>423</price>
                <volume-freezer>5</volume-freezer>
                <volume-not-freezer>15</volume-not-freezer>
            </refrigerator>
            <smoothing-iron>
                <type>Smoothing Iron</type>
                <id>5</id>
                <company>Honol</company>
                <name>Honol-3000</name>
                <price>230</price>
                <count-mode>3</count-mode>
                <max-temperature>250</max-temperature>
            </smoothing-iron>
            <refrigerator>
                <type>Refrigerator</type>
                <id>6</id>
                <company>Air</company>
                <name>Free air</name>
                <price>199.99</price>
                <volume-freezer>2</volume-freezer>
                <volume-not-freezer>2</volume-not-freezer>
            </refrigerator>
        </items>
</n:goods>
